apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-operator-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "endpoints", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["example.com"]
  resources: ["mysqls"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
