apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-operator-rb
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mysql-operator-role
subjects:
- kind: ServiceAccount
  name: mysql-operator-sa
  namespace: default
